{"timestamp": "2025-09-18T05:16:39.559134+09:00", "level": "ERROR", "name": "root", "message": "KRX API('삼성전자') 요청 중 오류: Expecting value: line 1 column 1 (char 0)", "source": "krx.py:159", "function": "get_stock_price", "exc_info": "Traceback (most recent call last):\n  File \"/home/masamong/masamong/venv/lib/python3.12/site-packages/requests/models.py\", line 976, in json\n    return complexjson.loads(self.text, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/json/__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/masamong/masamong/utils/api_handlers/krx.py\", line 135, in get_stock_price\n    stock_info_raw = await _get_price_from_krx(normalized_name)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/masamong/masamong/utils/api_handlers/krx.py\", line 126, in _get_price_from_krx\n    data = response.json()\n           ^^^^^^^^^^^^^^^\n  File \"/home/masamong/masamong/venv/lib/python3.12/site-packages/requests/models.py\", line 980, in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\nrequests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)", "trace_id": "N/A"}
{"timestamp": "2025-09-18T05:18:07.310801+09:00", "level": "ERROR", "name": "root", "message": "Foursquare API(35.6895,139.6917) 요청 중 오류: 401 Client Error: Unauthorized for url: https://api.foursquare.com/v3/places/search?ll=35.6895%2C139.6917&limit=10&sort=RELEVANCE&query=%EA%B4%80%EA%B4%91%EC%A7%80", "source": "foursquare.py:53", "function": "get_places_by_coords", "exc_info": "Traceback (most recent call last):\n  File \"/home/masamong/masamong/utils/api_handlers/foursquare.py\", line 36, in get_places_by_coords\n    response.raise_for_status()\n  File \"/home/masamong/masamong/venv/lib/python3.12/site-packages/requests/models.py\", line 1026, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.foursquare.com/v3/places/search?ll=35.6895%2C139.6917&limit=10&sort=RELEVANCE&query=%EA%B4%80%EA%B4%91%EC%A7%80", "trace_id": "N/A"}
{"timestamp": "2025-09-18T05:19:25.256534+09:00", "level": "ERROR", "name": "root", "message": "KRX API('하이닉스') 요청 중 오류: Expecting value: line 1 column 1 (char 0)", "source": "krx.py:159", "function": "get_stock_price", "exc_info": "Traceback (most recent call last):\n  File \"/home/masamong/masamong/venv/lib/python3.12/site-packages/requests/models.py\", line 976, in json\n    return complexjson.loads(self.text, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/json/__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/masamong/masamong/utils/api_handlers/krx.py\", line 135, in get_stock_price\n    stock_info_raw = await _get_price_from_krx(normalized_name)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/masamong/masamong/utils/api_handlers/krx.py\", line 126, in _get_price_from_krx\n    data = response.json()\n           ^^^^^^^^^^^^^^^\n  File \"/home/masamong/masamong/venv/lib/python3.12/site-packages/requests/models.py\", line 980, in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\nrequests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)", "trace_id": "N/A"}
